name: FarLanders
author: MJ Anglin
main: cc.farlanders.plugin.FarLanders
version: 1.0.0
api-version: 1.21
website: https://farlanders.cc

commands:
  farlanders:
    description: Main command for FarLanders plugin
    usage: /<command> <subcommand> [args...]
    aliases: [fl]
    permission: farlanders.command
    tab-complete: true

permissions:
  farlanders.command:
    description: Grants access to the main FarLanders command
    default: true

  farlanders.generate:
    description: Allows the use of the main FarLanders generate command
    default: op

  farlanders.tp:
    description: Allows the use of the teleport command
    default: op

  farlanders.admin:
    description: Grants access to administrative commands
    default: op

  farlanders.user:
    description: Grants access to user commands
    default: true

  farlanders.bypass:
    description: Allows users to bypass certain restrictions
    default: op
