name: FarLanders
author: MJ Anglin
main: cc.farlanders.plugin.FarLanders
version: 1.0.0
api-version: 1.21
website: https://farlanders.cc

commands:
  farlanders:
    description: Main command for FarLanders plugin
    usage: /<command> generate [worldName]
    aliases: [fl]
    permission: farlanders.command

permissions:
  farlanders.command:
    description: Allows the use of the main FarLanders command
    default: op

  farlanders.admin:
    description: Grants access to administrative commands
    default: op

  farlanders.user:
    description: Grants access to user commands
    default: true

  farlanders.bypass:
    description: Allows users to bypass certain restrictions
    default: false
